service: image-service

provider:
  name: aws
  region: "${env:AWS_REGION}"
  architecture: arm64

plugins:
  - serverless-better-credentials

functions:
  image-process:
    environment:
      CONNECTION_STRING: ${env:ATLAS_CONNECTION_STRING}
    url:
      cors: true
    image: "${env:REPOSITORY_TAG, '?????'}"