name: image-service-ci
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/image-service.yml'
      - 'image-service/src/**'
      - 'image-service/pom.xml'

jobs:
  ci:
    defaults:
      run:
        working-directory: image-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'image-service/pom.xml'
      - name: Run Tests
        run: mvn test